### ISSUE TITLE
Export namespace should be first transformed by `@babel/plugin-proposal-export-namespace-from`, when using Parcel

### ISSUE THREAD

**Issue by komodovaran** [vega/vega-embed#726]
Tested on a clean npm project, with only `npm init -y; npm install parcel-bundler vega-embed`.

If I try to import
```js
const vegaEmbed = require("vega-embed")
```

I get

```
🚨  /Users/joh/Documents/Code/vega_example/node_modules/vega-lite/build/src/log/index.js: /Users/joh/Documents/Code/vega_example/node_modules/vega-lite/build/src/log/index.js: Export namespace should be first transformed by `@babel/plugin-proposal-export-namespace-from`.
  17 | var _level;
  18 | import { Debug, Error as ErrorLevel, Info, logger, Warn } from 'vega-util';
> 19 | export * as message from './message';
     |        ^^^^^^^^^^^^
  20 | /**
  21 |  * Main (default) Vega Logger instance for Vega-Lite.
  22 |  */
  17 | var _level;
  18 | import { Debug, Error as ErrorLevel, Info, logger, Warn } from 'vega-util';
> 19 | export * as message from './message';
     |        ^^^^^^^^^^^^
  20 | /**
  21 |  * Main (default) Vega Logger instance for Vega-Lite.
  22 |  */
    at File.buildCodeFrameError (/Users/joh/Documents/Code/vega_example/node_modules/@babel/core/lib/transformation/file/file.js:244:12)
    at NodePath.buildCodeFrameError (/Users/joh/Documents/Code/vega_example/node_modules/@babel/traverse/lib/path/index.js:133:21)
    at assertExportSpecifier (/Users/joh/Documents/Code/vega_example/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:111:16)
    at /Users/joh/Documents/Code/vega_example/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:201:9
    at Array.forEach (<anonymous>)
    at /Users/joh/Documents/Code/vega_example/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:200:31
    at Array.forEach (<anonymous>)
    at getModuleMetadata (/Users/joh/Documents/Code/vega_example/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:148:27)
    at normalizeModuleAndLoadMetadata (/Users/joh/Documents/Code/vega_example/node_modules/@babel/helper-module-transforms/lib/normalize-and-load-metadata.js:57:7)
    at rewriteModuleStatementsAndPrepareHeader (/Users/joh/Documents/Code/vega_example/node_modules/@babel/helper-module-transforms/lib/index.js:75:54)
```

package.json:
```json
{
  "name": "vega_example",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "parcel index.html",
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "parcel-bundler": "^1.12.5",
    "vega-embed": "^6.18.2"
  }
}
```

**Comment by domoritz** [comment]
What's the action item here?

**Comment by domoritz** [comment]
Closing since this doesn't seem to be a problem with embed.
